# This is a basic workflow to help you get started with Actions

name: Pipeline
# Controls wehn the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch 
  push:
    branches: [ main ]
    paths:
    - Chapter15/**
    - .github/workflows/pipeline.yaml
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
  # EEnv to set reusable variables
env:
  ACRNAME: dmyacr

jobs:
  # this workflow contains a single job calleed "CI"
  CI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as a part of a job.
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git checkout
        uses: actions/checkout@v2
        
      - name: Azure Login
        uses: Azure/login@v1.4.4
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
